title: DongIn's Portfolio
page-top-title: DONGIN SONG
top-section-bg-text: "Keep Shipping, Keep Learning"
home-subtitle: DONGIN SONG&ensp;|&ensp;송동인
copyright-text: '&copy; DongInSong 2025-2026. All Rights Reserved.'