title: DongIn's Portfolio
page-top-title: DONGIN SONG
top-section-bg-text: "Keep Shipping, Keep Learning"
home-subtitle: DONGIN SONG&ensp;|&ensp;송동인
copyright-text: '&copy; Sen Li 2023-2025. All Rights Reserved.'